name: Container

on:
  - pull_request
  - push

jobs:
  build:
    name: "ðŸ“¦ Build container"
    runs-on: ubuntu-latest
    steps:

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Build the container
        run: docker build -t image-builder -f distribution/Dockerfile-ubi .

      - name: Run the container
        run: |
          docker run -d --net=host --name image-builder image-builder
          docker ps

      - name: Verify that the startup log line is in the logs
        run: |
          docker logs image-builder | grep "Starting image-builder server"

      - name: Check that the API is responding
        run: curl -sv http://127.0.0.1:8086/api/image-builder/v1/version

      - name: Stop the container
        run: docker stop --time 1 image-builder
