name: Coverity

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  scan:
    name: "coverity scan"
    runs-on: ubuntu-latest
    environment: coverity
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run coverify scan script
        env:
          COVERITY_SCAN_PROJECT_NAME: ${{ secrets.COVERITY_SCAN_PROJECT_NAME }}
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
          COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
        run: |
        
            echo "*** DEBUG: email=$COVERITY_EMAIL"
        
          echo "Downloading coverity scan package."
          curl -o /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64 \
            --form project="$COVERITY_SCAN_PROJECT_NAME" \
            --form token="$COVERITY_SCAN_TOKEN"
          tar xfz /tmp/cov-analysis-linux64.tgz
          mkdir bin
          cov-analysis-linux64-*/bin/cov-build --dir cov-int go build -o bin/ ./...
          tar cfz cov-int.tar.gz cov-int
          echo "Uploading coverity scan result to http://scan.coverity.com"
          curl https://scan.coverity.com/builds?project="$COVERITY_SCAN_PROJECT_NAME" \
            --form token="$COVERITY_SCAN_TOKEN" \
            --form email="$COVERITY_EMAIL" \
            --form file=@cov-int.tar.gz \
            --form version="$(git rev-parse HEAD)" \
            --form description="$GITHUB_REF / $GITHUB_SHA"
