name: Spec update

on:
  schedule:
    # Monday morning
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  scan:
    name: "spec update"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run tools/update-spec.sh
        run: |
          tools/update-spec.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-spec
          delete-branch: true
          title: "internal: update api specs"
          commit-message: "internal: update api specs"
          body: Composer api spec update.
          token: ${{ secrets.UPDATE_API_SPEC_TOKEN }}
          author: schutzbot <schutzbot@gmail.com>
